[build]
    command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
    publish = "dist"

[build.environment]
    NPM_FLAGS = "--version"

[functions]
    directory = "lambda"
    node_bundler = "esbuild"

[dev]
    command = "pnpm dev"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/buss/*"
    to = "https://buss.tonysull.co/:splat"
    status = 200