[build]
    command = "pnpm build"
    publish = "dist"

[functions]
    directory = "lambda"
    node_bundler = "esbuild"

[dev]
    command = "pnpm dev"

[[plugins]]
    package = "netlify-plugin-a11y"

[[plugins]]
    package = "netlify-plugin-cache-folder"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
