---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/data/card
  label: Cards
  create: documents
  match: "*.md"
  templates:
  - author
- type: directory
  path: src/data/entry
  label: Entries
  create: documents
  match: "**/*"
  templates:
  - photo
  - note
  - article
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
